### ISSUE TITLE
`cargo test` doesn't run `odra-vm`-based tests in user-defined contract

### ISSUE THREAD

**Issue by zie1ony** [odradev/odra#306] opened 2024-01-03 00:21 UTC
I just noticed this. Let's discuss.

**Comment by kubaplas** [comment] 2024-01-05 10:52
This is caused by missing `--lib` at the end - it tries to build bins first.
To solve this, we need to turn off bin tests in Cargo.toml

**Comment by kubaplas** [comment] 2024-01-25 10:40
Fixed with #307

**Closed as completed by kubaplas** 2024-01-25 10:40 UTC
