### ISSUE TITLE
Provide full path to `BTreeSet` in autogenerated code.

### ISSUE THREAD

**Issue by zie1ony** [odradev/odra#363] opened 2024-02-19 15:06 UTC
This simple module:
```rust
use odra::SubModule;
use odra_modules::{self, erc20::Erc20};

#[odra::module]
pub struct DontBuyMe {
    token: SubModule<Erc20>,
}
```
yelds error:
```
consider importing one of these items: `use odra::prelude::BTreeSet;`, `use std::collections::BTreeSet;
```

I think the solution is to use full path from `odra::prelude` in autogenerated code.

**Comment by kpob** [comment] 2024-05-08 08:40
Duplicate of #403

**Closed as completed by kpob** 2024-05-08 08:40 UTC
Labels: bug, macro
